# Generated by Django 3.0.3 on 2020-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='test@test.com', max_length=100),
            preserve_default=False,
        ),
    ]
